### ISSUE TITLE
High risk vulnerabilities in dependencies

### ISSUE THREAD

**Issue by defijesus** [SetProtocol/index-ui#183]
As the website integrates with the user wallet, we must be very careful to not introduce any attack vectors that could put our users funds in danger.

After running npm audit I found one that should be solved ASAP:

web3 package has a vulnerability that may leak the private keys. The [vulnerability page](https://npmjs.com/advisories/877) states the following:    
> Exploiting this vulnerability likely requires a Cross-Site Scripting vulnerability to access the private key.

Other notable vulnerabilities:

- axios - [Server Side Request Forgery](https://npmjs.com/advisories/1594)
- elliptic - [Usage of broken or risky crypto algos](https://npmjs.com/advisories/1648) and [Signature Malleability]( https://npmjs.com/advisories/1547)

**Comment by 0xModene** [comment]
Go ahead and make a fork. Since this project uses `yarn`, run the following before you make any other dependency changes:

`npm i --package-lock-only && rm yarn.lock && npm audit fix && yarn import && rm package-lock.json`

That should install an npm `package-lock.json`, do the npm audit fix to clear up any non-breaking changes, and then reinstall the `yarn.lock` file like nothing happened.
